# Generated by Django 2.2 on 2021-07-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Staus post', 'verbose_name_plural': 'Staus posts'},
        ),
    ]
